# Generated by Django 3.0.5 on 2020-06-20 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200513_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 17, 8, 52, 868516, tzinfo=utc), verbose_name='کاربر ویژه تا '),
        ),
    ]
