# Generated by Django 3.0.5 on 2020-11-07 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200802_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 13, 45, 35, 248994, tzinfo=utc), verbose_name='کاربر ویژه تا '),
        ),
    ]
