# Generated by Django 3.0.5 on 2020-11-19 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201107_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 53, 44, 456290, tzinfo=utc), verbose_name='کاربر ویژه تا '),
        ),
    ]
