# Generated by Django 3.0.5 on 2020-11-19 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201119_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='special_user',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 56, 37, 168677, tzinfo=utc), verbose_name='کاربر ویژه تا '),
        ),
    ]
