# Generated by Django 3.0.5 on 2020-04-12 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 17, 34, 38, 862824, tzinfo=utc)),
        ),
    ]
