# Generated by Django 3.0.5 on 2020-04-12 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200412_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 20, 8, 42, 200644, tzinfo=utc)),
        ),
    ]
