# Generated by Django 3.0.5 on 2020-04-20 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200420_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 18, 56, 43, 606799, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
