# Generated by Django 3.0.5 on 2020-04-20 22:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20200420_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 23, 38, 419556, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
