# Generated by Django 3.0.5 on 2020-04-20 22:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200421_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auth',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 27, 42, 747602, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
