# Generated by Django 3.0.5 on 2020-04-20 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200421_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 29, 44, 652613, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
