# Generated by Django 3.0.5 on 2020-11-19 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201107_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 53, 44, 469286, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
